// ============================================================
// CATÁLOGO DE SERVICIOS RESERVABLES
// ------------------------------------------------------------
// Nombres, categorías y precios sacados de servicios.html.
// Duraciones: la mayoría vienen directas de lo que indicaste; las
// marcadas [ESTIMADO] son una suposición razonable mía porque no se
// dio un dato exacto — confírmalas o cámbialas cuando puedas, no
// hace falta tocar nada más.
//
// Nota: por ahora cada tratamiento es una sesión suelta (el precio
// "1 sesión" de la tabla). Los precios de bono/3 sesiones de
// servicios.html no están aquí — si quieres vender bonos desde la
// reserva online, dímelo y lo añadimos como algo aparte.
//
// paymentPolicy:
//   "deposit_required"  -> hay que pagar el % de seña sí o sí para reservar
//   "full_required"     -> hay que pagar el 100% online para reservar
//   "deposit_or_full"    -> el cliente elige: paga solo la seña o el total
//
// depositPercent: porcentaje de seña (solo se usa si aplica según paymentPolicy)
// ============================================================

module.exports = [
  // ── 01 · DEPILACIÓN LÁSER SHR ──
  // Duración por tamaño de zona: pequeña 20 min / media 30 min / cuerpo completo 60 min.
  // He repartido cada zona de la tabla real por tamaño aproximado — revisa el reparto.
  { id: 'laser-labio', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Labio', nameEn: 'Lip', nameIt: 'Labbro', durationMinutes: 20, price: 20, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-menton', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Mentón', nameEn: 'Chin', nameIt: 'Mento', durationMinutes: 20, price: 20, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-linea-alba', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Línea alba', nameEn: 'Linea alba', nameIt: 'Linea alba', durationMinutes: 20, price: 20, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-ingles', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Ingles', nameEn: 'Groin', nameIt: 'Inguine', durationMinutes: 20, price: 35, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-axilas', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Axilas', nameEn: 'Underarms', nameIt: 'Ascelle', durationMinutes: 20, price: 35, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-facial', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Facial', nameEn: 'Face', nameIt: 'Viso', durationMinutes: 30, price: 50, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-intimo-completo', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Íntimo completo', nameEn: 'Full intimate', nameIt: 'Inguine completo', durationMinutes: 30, price: 50, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-medios-brazos', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Medios brazos', nameEn: 'Half arms', nameIt: 'Mezze braccia', durationMinutes: 30, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-gluteos', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Glúteos', nameEn: 'Glutes', nameIt: 'Glutei', durationMinutes: 30, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-medias-piernas', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Medias piernas', nameEn: 'Half legs', nameIt: 'Mezze gambe', durationMinutes: 30, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-brazos', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Brazos', nameEn: 'Arms', nameIt: 'Braccia', durationMinutes: 40, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-pecho-abdomen', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Pecho y abdomen', nameEn: 'Chest and abdomen', nameIt: 'Petto e addome', durationMinutes: 40, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-espalda', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Espalda', nameEn: 'Back', nameIt: 'Schiena', durationMinutes: 40, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-piernas-completas', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Piernas completas', nameEn: 'Full legs', nameIt: 'Gambe complete', durationMinutes: 40, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laser-cuerpo-completo', category: 'Depilación Láser SHR', categoryEn: 'SHR Laser Hair Removal', categoryIt: 'Depilazione Laser SHR', name: 'Cuerpo completo', nameEn: 'Full body', nameIt: 'Corpo completo', durationMinutes: 80, price: 210, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 02 · HILO & LIFTING ──
  { id: 'hilo-labio', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Labio (hilo)', nameEn: 'Lip (thread)', nameIt: 'Labbro (filo)', durationMinutes: 10, price: 5, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'hilo-menton', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Mentón (hilo)', nameEn: 'Chin (thread)', nameIt: 'Mento (filo)', durationMinutes: 10, price: 5, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'hilo-cejas', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Cejas (hilo)', nameEn: 'Eyebrows (thread)', nameIt: 'Sopracciglia (filo)', durationMinutes: 20, price: 15, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'hilo-cejas-labio-menton', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Cejas Esenciales (hilo: cejas + labio + mentón)', nameEn: 'Brows Essentials (thread: eyebrows + lip + chin)', nameIt: 'Sopracciglia Essenziali (filo: sopracciglia + labbro + mento)', durationMinutes: 30, price: 22, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'henna-cejas', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Henna', nameEn: 'Henna', nameIt: 'Henné', durationMinutes: 30, price: 25, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'hilo-facial', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Facial (hilo)', nameEn: 'Face (thread)', nameIt: 'Viso (filo)', durationMinutes: 30, price: 30, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'lifting-pestanas-tradicional', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Lifting de pestañas tradicional', nameEn: 'Traditional eyelash lifting', nameIt: 'Lifting ciglia tradizionale', durationMinutes: 45, price: 35, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'laminado-cejas', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Laminado de cejas', nameEn: 'Brow lamination', nameIt: 'Laminazione sopracciglia', durationMinutes: 45, price: 35, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'lifting-pestanas-coreano', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Lifting de pestañas coreano', nameEn: 'Korean eyelash lifting', nameIt: 'Lifting ciglia coreano', durationMinutes: 45, price: 40, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'brows-basic', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Cejas Básicas (hilo + lifting coreano)', nameEn: 'Brows Basic (thread eyebrows + Korean lifting)', nameIt: 'Sopracciglia Base (filo + lifting coreano)', durationMinutes: 60, price: 45, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'brows-glam', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Cejas Definidas (hilo + henna + lifting coreano)', nameEn: 'Brows Glam (thread eyebrows + henna + Korean lifting)', nameIt: 'Sopracciglia Definite (filo + henné + lifting coreano)', durationMinutes: 60, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'brows-signature', category: 'Hilo & Lifting', categoryEn: 'Threading & Lifting', categoryIt: 'Filo & Lifting', name: 'Cejas Impactantes (hilo + lifting trad. + laminado + tinte)', nameEn: 'Brows Signature (thread + traditional lifting + lamination + tint)', nameIt: 'Sopracciglia Impattanti (filo + lifting trad. + laminazione + tinta)', durationMinutes: 60, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 03 · FACIALES & APARATOLOGÍA ── (todos 60 min, según indicaste)
  { id: 'diagnostico-facial-ia', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Diagnóstico facial con IA', nameEn: 'AI facial diagnosis', nameIt: 'Diagnosi del viso con IA', durationMinutes: 60, price: 25, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'radiofrecuencia-facial', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Radiofrecuencia facial', nameEn: 'Facial radiofrequency', nameIt: 'Radiofrequenza viso', durationMinutes: 60, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'limpieza-profunda', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Limpieza facial profunda', nameEn: 'Deep facial cleansing', nameIt: 'Pulizia viso profonda', durationMinutes: 60, price: 65, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'peeling-quimico', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Peeling químico personalizado', nameEn: 'Custom chemical peel', nameIt: 'Peeling chimico personalizzato', durationMinutes: 60, price: 65, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'hollywood-peel', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Hollywood Peel', nameEn: 'Hollywood Peel', nameIt: 'Hollywood Peel', durationMinutes: 60, price: 70, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'limpieza-facial-premium', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Limpieza facial premium (Limpieza facial profunda + Hollywood Peel)', nameEn: 'Premium facial cleansing (Deep facial cleansing + Hollywood Peel)', nameIt: 'Pulizia viso premium (Pulizia viso profonda + Hollywood Peel)', durationMinutes: 90, price: 95, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'dermapen', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Dermapen', nameEn: 'Dermapen', nameIt: 'Dermapen', durationMinutes: 60, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'mesoterapia-virtual', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Mesoterapia virtual', nameEn: 'Virtual mesotherapy', nameIt: 'Mesoterapia virtuale', durationMinutes: 60, price: 85, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'fotorejuvenecimiento-ipl', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Fotorejuvenecimiento (IPL)', nameEn: 'Photorejuvenation (IPL)', nameIt: 'Fotoringiovanimento (IPL)', durationMinutes: 60, price: 100, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'exosomas-dermapen', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Exosomas + PDRN con Dermapen PRO', nameEn: 'Exosomes + PDRN with Dermapen PRO', nameIt: 'Esosomi + PDRN con Dermapen PRO', durationMinutes: 60, price: 140, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'ritual-basic-skin', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Ritual Esencial (limpieza + dermaplaning)', nameEn: 'Ritual Basic Skin (cleansing + dermaplaning)', nameIt: 'Ritual Essenziale (pulizia + dermaplaning)', durationMinutes: 90, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'ritual-relaxing', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Ritual Hidratante Intensivo (dermaplaning + hidratación + masaje)', nameEn: 'Ritual Hidra-Relax (dermaplaning + hydration + massage)', nameIt: 'Ritual Idratante Intensivo (dermaplaning + idratazione + massaggio)', durationMinutes: 90, price: 80, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'ritual-flash-lifting', category: 'Faciales & Aparatología', categoryEn: 'Facials & Devices', categoryIt: 'Viso & Aparatologia', name: 'Ritual Lifting Exprés (limpieza + radiofrecuencia + maderoterapia)', nameEn: 'Ritual Flash Lifting (cleansing + radiofrequency + wood therapy)', nameIt: 'Ritual Lifting Express (pulizia + radiofrequenza + maderoterapia)', durationMinutes: 100, price: 110, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 04 · PROGRAMAS FACIALES ── (todos 1h40 min, según indicaste)
  { id: 'programa-periocular', category: 'Programas Faciales', categoryEn: 'Facial Programs', categoryIt: 'Programmi Viso', name: 'Programa Periocular', nameEn: 'Periocular Program', nameIt: 'Programma Perioculare', durationMinutes: 100, price: 250, paymentPolicy: 'deposit_or_full', depositPercent: 30, description: 'Incluye diagnóstico facial con IA + 3 sesiones de peeling químico y exosomas para el contorno de ojos.', descriptionEn: 'Includes AI facial diagnosis + 3 chemical peel and exosome sessions for the eye contour.', descriptionIt: 'Include diagnosi del viso con IA + 3 sedute di peeling chimico ed esosomi per il contorno occhi.' },
  { id: 'programa-glow-skin', category: 'Programas Faciales', categoryEn: 'Facial Programs', categoryIt: 'Programmi Viso', name: 'Programa Piel Radiante', nameEn: 'Glow Skin Program', nameIt: 'Programma Pelle Radiosa', durationMinutes: 100, price: 310, paymentPolicy: 'deposit_or_full', depositPercent: 30, description: 'Incluye diagnóstico facial con IA + 2 Hollywood Peel + 1 IPL o peeling + 2 Dermapen con vitamina C.', descriptionEn: 'Includes AI facial diagnosis + 2 Hollywood Peel + 1 IPL or peel + 2 vitamin C Dermapen sessions.', descriptionIt: 'Include diagnosi del viso con IA + 2 Hollywood Peel + 1 IPL o peeling + 2 Dermapen con vitamina C.' },
  { id: 'programa-anti-aging', category: 'Programas Faciales', categoryEn: 'Facial Programs', categoryIt: 'Programmi Viso', name: 'Programa Antiedad', nameEn: 'Anti-Aging Program', nameIt: 'Programma Anti-age', durationMinutes: 100, price: 430, paymentPolicy: 'deposit_or_full', depositPercent: 30, description: 'Incluye diagnóstico facial con IA + 3 sesiones de peeling químico y exosomas con PDRN + 3 sesiones de radiofrecuencia.', descriptionEn: 'Includes AI facial diagnosis + 3 chemical peel and PDRN exosome sessions + 3 radiofrequency sessions.', descriptionIt: 'Include diagnosi del viso con IA + 3 sedute di peeling chimico ed esosomi con PDRN + 3 sedute di radiofrequenza.' },
  { id: 'programa-control-acne', category: 'Programas Faciales', categoryEn: 'Facial Programs', categoryIt: 'Programmi Viso', name: 'Programa Control Acné', nameEn: 'Acne Control Program', nameIt: 'Programma Controllo Acne', durationMinutes: 100, price: 460, paymentPolicy: 'deposit_or_full', depositPercent: 30, description: 'Incluye diagnóstico facial con IA + limpieza profunda + 3 Hollywood Peel + 3 peeling químico salicílico + 3 Dermapen con ácido salicílico.', descriptionEn: 'Includes AI facial diagnosis + deep cleansing + 3 Hollywood Peel + 3 salicylic chemical peel + 3 salicylic acid Dermapen sessions.', descriptionIt: 'Include diagnosi del viso con IA + pulizia profonda + 3 Hollywood Peel + 3 peeling chimico salicilico + 3 Dermapen con acido salicilico.' },
  // "Programa Melasma Slow" y "Programa Melasma Intensive" son precio "a consultar" en la
  // web — no están aquí porque el sistema necesita un precio fijo para cobrar online.
  // Si me das un precio (aunque sea orientativo) los añado igual que los demás.

  // ── 05 · CORPORALES ──
  { id: 'presoterapia', category: 'Corporales', categoryEn: 'Body Treatments', categoryIt: 'Corpo', name: 'Presoterapia · 30 min', nameEn: 'Pressotherapy · 30 min', nameIt: 'Pressoterapia · 30 min', durationMinutes: 30, price: 30, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'radiofrecuencia-corporal', category: 'Corporales', categoryEn: 'Body Treatments', categoryIt: 'Corpo', name: 'Radiofrecuencia corporal · 45 min', nameEn: 'Body radiofrequency · 45 min', nameIt: 'Radiofrequenza corporea · 45 min', durationMinutes: 45, price: 70, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'maderoterapia', category: 'Corporales', categoryEn: 'Body Treatments', categoryIt: 'Corpo', name: 'Maderoterapia · 50 min', nameEn: 'Wood therapy · 50 min', nameIt: 'Maderoterapia · 50 min', durationMinutes: 50, price: 85, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'drenaje-linfatico-50', category: 'Corporales', categoryEn: 'Body Treatments', categoryIt: 'Corpo', name: 'Drenaje linfático terapéutico · 50 min', nameEn: 'Therapeutic lymphatic drainage · 50 min', nameIt: 'Drenaggio linfatico terapeutico · 50 min', durationMinutes: 50, price: 75, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'drenaje-linfatico-manuela-shala', category: 'Corporales', categoryEn: 'Body Treatments', categoryIt: 'Corpo', name: 'Drenaje linfático método "Manuela Shala" · 50 min', nameEn: '"Manuela Shala" method lymphatic drainage · 50 min', nameIt: 'Drenaggio linfatico metodo "Manuela Shala" · 50 min', durationMinutes: 50, price: 120, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 06 · MASAJES ── (ya no se trabaja con Essentia — todos exclusivos de Anna, ver employees.js)
  { id: 'masaje-relajante-60', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Masaje relajante · 60 min', nameEn: 'Relaxing massage · 60 min', nameIt: 'Massaggio rilassante · 60 min', durationMinutes: 60, price: 65, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'masaje-aromaterapia-60', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Masaje aromaterapia · 60 min', nameEn: 'Aromatherapy massage · 60 min', nameIt: 'Massaggio aromaterapico · 60 min', durationMinutes: 60, price: 70, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'masaje-personalizado-60', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Masaje personalizado · 60 min', nameEn: 'Personalized massage · 60 min', nameIt: 'Massaggio personalizzato · 60 min', durationMinutes: 60, price: 80, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  // Tratamiento de 45 min, pero se bloquean 55 min en la agenda para dar tiempo a preparar la cabina
  { id: 'kobido-facial', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Kobido facial · 45 min', nameEn: 'Kobido facial massage · 45 min', nameIt: 'Kobido facciale · 45 min', durationMinutes: 55, price: 80, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'lifting-facial', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Lifting facial · 45 min', nameEn: 'Facial lifting massage · 45 min', nameIt: 'Lifting facciale · 45 min', durationMinutes: 55, price: 80, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'reflexologia-podal-60', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Reflexología podal · 60 min', nameEn: 'Foot reflexology · 60 min', nameIt: 'Riflessologia plantare · 60 min', durationMinutes: 60, price: 70, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'reflexologia-podal-50', category: 'Masajes', categoryEn: 'Massages', categoryIt: 'Massaggi', name: 'Reflexología podal · 50 min', nameEn: 'Foot reflexology · 50 min', nameIt: 'Riflessologia plantare · 50 min', durationMinutes: 50, price: 60, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 07 · ELIMINACIÓN DE TATUAJES ──
  // Mapeé tus tamaños (xs/s/m/grande) a los de la tabla real (S/M/L/XL) de menor a mayor.
  { id: 'tatuaje-talla-s', category: 'Eliminación de tatuajes', categoryEn: 'Tattoo Removal', categoryIt: 'Rimozione tatuaggi', name: 'Talla S · hasta 4×4 cm', nameEn: 'Size S · up to 4×4 cm', nameIt: 'Taglia S · fino a 4×4 cm', durationMinutes: 10, price: 45, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'eliminacion-micropigmentacion', category: 'Eliminación de tatuajes', categoryEn: 'Tattoo Removal', categoryIt: 'Rimozione tatuaggi', name: 'Eliminación micropigmentación', nameEn: 'Microblading removal', nameIt: 'Rimozione micropigmentazione', durationMinutes: 20, price: 70, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'tatuaje-talla-m', category: 'Eliminación de tatuajes', categoryEn: 'Tattoo Removal', categoryIt: 'Rimozione tatuaggi', name: 'Talla M · hasta 8×8 cm', nameEn: 'Size M · up to 8×8 cm', nameIt: 'Taglia M · fino a 8×8 cm', durationMinutes: 20, price: 80, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'tatuaje-talla-l', category: 'Eliminación de tatuajes', categoryEn: 'Tattoo Removal', categoryIt: 'Rimozione tatuaggi', name: 'Talla L · hasta 15×15 cm', nameEn: 'Size L · up to 15×15 cm', nameIt: 'Taglia L · fino a 15×15 cm', durationMinutes: 30, price: 120, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'tatuaje-talla-xl', category: 'Eliminación de tatuajes', categoryEn: 'Tattoo Removal', categoryIt: 'Rimozione tatuaggi', name: 'Talla XL · más de 15×15 cm', nameEn: 'Size XL · over 15×15 cm', nameIt: 'Taglia XL · oltre 15×15 cm', durationMinutes: 60, price: 170, paymentPolicy: 'deposit_or_full', depositPercent: 30 },

  // ── 08 · MICROPIGMENTACIÓN ──
  { id: 'valoracion-micropigmentacion', category: 'Micropigmentación', categoryEn: 'Microblading', categoryIt: 'Micropigmentazione', name: 'Valoración de micropigmentación', nameEn: 'Microblading assessment', nameIt: 'Valutazione micropigmentazione', durationMinutes: 30, price: 0, paymentPolicy: 'deposit_or_full', depositPercent: 0 },
  { id: 'retoque-micropigmentacion', category: 'Micropigmentación', categoryEn: 'Microblading', categoryIt: 'Micropigmentazione', name: 'Retoque micropigmentación anual', nameEn: 'Annual microblading touch-up', nameIt: 'Ritocco micropigmentazione annuale', durationMinutes: 120, price: 150, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
  { id: 'micropigmentacion-cejas-retoque', category: 'Micropigmentación', categoryEn: 'Microblading', categoryIt: 'Micropigmentazione', name: 'Micropigmentación cejas + retoque', nameEn: 'Eyebrow microblading + touch-up', nameIt: 'Micropigmentazione sopracciglia + ritocco', durationMinutes: 210, price: 300, paymentPolicy: 'deposit_or_full', depositPercent: 30 },
];
